version: "2"
services :
  proxy:
      restart: on-failure:5
      image: jwilder/nginx-proxy:alpine
      ports :
        - 80:80
      volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
      networks:
        - www
networks:
  www:
    external: true
