#!/bin/bash
usage="$(basename "$0") gravName user cmd [args] on the given docker compose name.

      e.g., $(basename "$0") mygrav www bin/grav install
"

# Checks there is at least one arg
if [ $# -lt 3 ]; then
    echo "Wrong nomber of argument (expect at least gravname, user and cmd)"
    echo "was provided : $*"
    echo $usage;
    exit 1
fi

DOCKERNAME=$1
NAME="$1_php_1";

# Checks the given docker is running
if [ "$(sudo docker ps -f name=$NAME|wc -l)" -lt 2 ]; then
    echo "no running container for given name \"$1\" (more precisely no \"$NAME\" container)"
    echo "arguments provided : $*"
    echo $usage;
    exit 1
fi

ARGS=${@:3}
USER=$2
echo "$USER@$NAME\$> $ARGS"
sudo docker exec -it $NAME /bin/sh -c "(cd /www/$DOCKERNAME/ && su-exec $USER $ARGS)"
