#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
usage="$(basename "$0") -- call gpm on the given docker compose name"
DOCKERNAME=$1
CMD="/www/$DOCKERNAME/bin/gpm"
ARGS="${@:2}"
(cd $DIR && ./exec $1 $CMD $ARGS)
