#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
usage="$(basename "$0") -- call /bin/bash on the given docker compose name"
CMD="/bin/bash"
DOCKERNAME=$1
ARGS="${@:2}"
(cd $DIR && ./exec $DOCKERNAME $CMD $ARGS)
